### ISSUE TITLE
Input files

### ISSUE THREAD

**Issue by ParivashFeyzishendi** [naotohori/16S-central-folding#2]
Hi, 
Thank you for providing the code.
I have a question about the generation of two input files located in the src folder: unprocessed_bond.dat and unprocessed_stack.dat. How these files are created? 
(I used WHAT IF server as mentioned in the article but it was not successful)

Thanks, 
Parivash

**Comment by naotohori** [comment]
Hi Parivash, those two files were created by one of the coauthors, presumably using some scripts but I don't have access to them anymore.

For the hydrogen bonding list (_bonds.dat), I'm sure that she used the WHAT-IF server, but it seems neither [Optimal Hydrogen Bonding Network](https://swift.cmbi.umcn.nl/servers/html/hnet.html) nor [Potential Hydrogen Bonds](https://swift.cmbi.umcn.nl/servers/html/allhbonds.html) are working now. Alternatively you can use [x3dna](https://x3dna.org/) to generate a list of hydrogen bonds and stacking for a given structure. In either case, you will need a script to convert it into the format for this program. 

In the hydrogen bonds list, each row corresponds to a list of atom pairs that form hydrogen bond between two nucleotides. The atom lists follow a type and nucleotide IDs, and are followd by "TER".  Type "NON00" indicates hydrogen bonds formed in the PDB stuctrure. Other types "CAN" are possible canonical base pairs with numbers indicating either A-U, G-C, and G-U.

In the stacking list, these are nucleotides forming tertiary stacking (stacking between non-consecutive nucleotides) formed in the PDB structure. The sign (+/-) should indicate which side of the base is forming the stacking interaction.
